### ISSUE TITLE
Problem in Running Multi-Agent ACKTR

### ISSUE THREAD

**Issue by LTGgeek** [ermongroup/MA-AIRL#2]
Hi author!

Here is a problem when I were running `python -m sandbox.mack.run_simple`. 
Here is the log:

```
logging to: /atlas/u/lantaoyu
Traceback (most recent call last):
  File "/home/teng/anaconda3/envs/tensorflow/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/teng/anaconda3/envs/tensorflow/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/teng/Desktop/MA-AIRL-master/multi-agent-irl/sandbox/mack/run_simple.py", line 63, in <module>
    main()
  File "/home/teng/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/teng/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/teng/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/teng/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/teng/Desktop/MA-AIRL-master/multi-agent-irl/sandbox/mack/run_simple.py", line 58, in main
    train(logdir + '/exps/mack/' + env_id + '/l-{}-b-{}/seed-{}'.format(lr, batch_size, seed),
TypeError: must be str, not NoneType
```

What's wrong with it?

**Comment by XuandongZhao** [comment]
have the same problem on mac os

**Comment by moonsh** [comment]
I got the same error

**Comment by to1a** [comment]
I think the reason is that they use the `click` module to pass parameters to the script, and the parameter `env` does not have a default value, then the `env` got a NoneType. Simply add a default value like other parameters would solve this issue, or manually set a value for the parameter `env` when starting the program:
`python -m sandbox.mack.run_simple --env simple #an example`

**Comment by Cakhavan** [comment]
I reached about here in the project's code where I ran to1a's line python -m sandbox.mack.run_simple --env simple.

However, I get the following errors:

   raise error.Error('Attempted to look up malformed environment ID: {}. (Currently all IDs must be of the form {}.)'.format(id.encode('utf-8'), env_id_re.pattern))
gym.error.Error: Attempted to look up malformed environment ID: b'simple'. (Currently all IDs must be of the form ^(?:[\w:-]+\/)?([\w:.-]+)-v(\d+)$.)

I modified the script's code from env = gym.make_env(env_id) to env = gym.make(env_id) to avoid versioning issues, but I don't believe this to be the source of the error. I believe the way the code is feeding in the environment ID is missing a step because it seems to be just making the environment from the name 'simple' alone, which doesn't make too much sense to me.

May someone explain this one to me?

Thanks!

**Comment by pythlang** [comment]
![image](https://user-images.githubusercontent.com/23020467/193280619-b97df24e-bc74-4ab2-bfe7-8621f5b18925.png)

**Comment by pythlang** [comment]
I then ran into `make_env.get_identical()` was missing.

**Comment by stellaxzhu334** [comment]
> I think the reason is that they use the `click` module to pass parameters to the script, and the parameter `env` does not have a default value, then the `env` got a NoneType. Simply add a default value like other parameters would solve this issue, or manually set a value for the parameter `env` when starting the program: `python -m sandbox.mack.run_simple --env simple #an example`

I got this error after running the suggestion command. OSError: [Errno 30] Read-only file system: '/atlas'. Any suggestions? Thank!
