### ISSUE TITLE
Error running run_mack_airl.py ,No such file "checkpoint20000-1000tra.pkl"

### ISSUE THREAD

**Issue by HanamaruK** [ermongroup/MA-AIRL#5]
I played `python -m sandbox.mack.run_simple --env simple_spread` and obtained the movement of the expert. 
But I can't play `python -m irl.mack.run_mack_airl`.
On the error screen, 

>Traceback (most recent call last):
  File "/root/local/python-3.6.5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/local/python-3.6.5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/local/Labo/MA-AIRL/multi-agent-irl/irl/mack/run_mack_airl.py", line 77, in <module>
    main()
  File "/root/local/python-3.6.5/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/root/local/python-3.6.5/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/root/local/python-3.6.5/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/local/python-3.6.5/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/root/local/Labo/MA-AIRL/multi-agent-irl/irl/mack/run_mack_airl.py", line 73, in main
    rew_scale=rew_scale)
  File "/root/local/Labo/MA-AIRL/multi-agent-irl/irl/mack/run_mack_airl.py", line 38, in train
    expert = MADataSet(expert_path, ret_threshold=ret_threshold, traj_limitation=traj_limitation, nobs_flag=True)
  File "/root/local/Labo/MA-AIRL/multi-agent-irl/irl/dataset.py", line 84, in __init__
    with open(expert_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/atlas/u/lantaoyu/projects/MA-AIRL/mack/simple_spread/l-0.1-b-1000/seed-1/checkpoint20000-1000tra.pkl'

How can I create "checkpoint20000-1000tra.pkl"?
What's wrong with it?

**Comment by Crazyalltnt** [comment]
same problem

**Comment by davidmccl** [comment]
To obtain the .pkl file you need to run 'python -m irl.render --env simple_spread' and then run 'python -m irl.mack.run_mack_airl'. Check that expert_path is set to the .pkl file.  You need to uncomment line 118 in rl/render.py

**Comment by hxmzj** [comment]
> To obtain the .pkl file you need to run 'python -m irl.render --env simple_spread' and then run 'python -m irl.mack.run_mack_airl'. Check that expert_path is set to the .pkl file. You need to uncomment line 118 in rl/render.py

FileNotFoundError: [Errno 2] No such file or directory: '../sandbox/mack/atlas/u/lantaoyu/exps/airl/simple_spread/decentralized/s-200/l-0.1-b-1000-d-0.1-c-500-l2-0.1-iter-1-r-0.0/seed-2/m_24000'

why？
